# This is a config for E2B sandbox template.
# You can use template ID (5cu4rqmlwqfj7ew1jnad) or template name (vibe-nextjs-aurexoai-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-aurexoai-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-aurexoai-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-aurexoai-2')

team_id = "45ef509c-6706-4015-9718-e014b305a90c"
start_cmd = "compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-aurexoai-2"
template_id = "5cu4rqmlwqfj7ew1jnad"
